IMAGE hint_01_pc  "../../data/pc/hint/01.bmp"   0
IMAGE hint_02_pc  "../../data/pc/hint/02.bmp"   0
IMAGE hint_03_pc  "../../data/pc/hint/03.bmp"   0
IMAGE hint_04_pc  "../../data/pc/hint/04.bmp"   0
IMAGE hint_05_pc  "../../data/pc/hint/05.bmp"   0
IMAGE hint_06_pc  "../../data/pc/hint/06.bmp"   0
IMAGE hint_07_pc  "../../data/pc/hint/07.bmp"   0
IMAGE hint_08_pc  "../../data/pc/hint/08.bmp"   0
IMAGE hint_09_pc  "../../data/pc/hint/09.bmp"   0
