IMAGE hint_01_msx "../../data/msx/hint/01.bmp"  1
IMAGE hint_02_msx "../../data/msx/hint/02.bmp"  1
IMAGE hint_03_msx "../../data/msx/hint/03.bmp"  1
IMAGE hint_04_msx "../../data/msx/hint/04.bmp"  1
IMAGE hint_05_msx "../../data/msx/hint/05.bmp"  1
IMAGE hint_06_msx "../../data/msx/hint/06.bmp"  1
IMAGE hint_07_msx "../../data/msx/hint/07.bmp"  1
IMAGE hint_08_msx "../../data/msx/hint/08.bmp"  1
IMAGE hint_09_msx "../../data/msx/hint/09.bmp"  1
