IMAGE hint_01_cga  "../../data/cga/hint/01.bmp"   1
IMAGE hint_02_cga  "../../data/cga/hint/02.bmp"   1
IMAGE hint_03_cga  "../../data/cga/hint/03.bmp"   1
IMAGE hint_04_cga  "../../data/cga/hint/04.bmp"   1
IMAGE hint_05_cga  "../../data/cga/hint/05.bmp"   1
IMAGE hint_06_cga  "../../data/cga/hint/06.bmp"   1
IMAGE hint_07_cga  "../../data/cga/hint/07.bmp"   1
IMAGE hint_08_cga  "../../data/cga/hint/08.bmp"   1
IMAGE hint_09_cga  "../../data/cga/hint/09.bmp"   1
