IMAGE hint_01_pcw  "../../data/pcw/hint/01.bmp"   1
IMAGE hint_02_pcw  "../../data/pcw/hint/02.bmp"   1
IMAGE hint_03_pcw  "../../data/pcw/hint/03.bmp"   1
IMAGE hint_04_pcw  "../../data/pcw/hint/04.bmp"   1
IMAGE hint_05_pcw  "../../data/pcw/hint/05.bmp"   1
IMAGE hint_06_pcw  "../../data/pcw/hint/06.bmp"   1
IMAGE hint_07_pcw  "../../data/pcw/hint/07.bmp"   1
IMAGE hint_08_pcw  "../../data/pcw/hint/08.bmp"   1
IMAGE hint_09_pcw  "../../data/pcw/hint/09.bmp"   1
