IMAGE hint_01_nes "../../data/nes/hint/01.bmp" -1
IMAGE hint_02_nes "../../data/nes/hint/02.bmp" -1
IMAGE hint_03_nes "../../data/nes/hint/03.bmp" -1
IMAGE hint_04_nes "../../data/nes/hint/04.bmp" -1
IMAGE hint_05_nes "../../data/nes/hint/05.bmp" -1
IMAGE hint_06_nes "../../data/nes/hint/06.bmp" -1
IMAGE hint_07_nes "../../data/nes/hint/07.bmp" -1
IMAGE hint_08_nes "../../data/nes/hint/08.bmp" -1
IMAGE hint_09_nes "../../data/nes/hint/09.bmp" -1
