IMAGE hint_01_gb  "../../data/gb/hint/01.bmp"  -1
IMAGE hint_02_gb  "../../data/gb/hint/02.bmp"  -1
IMAGE hint_03_gb  "../../data/gb/hint/03.bmp"  -1
IMAGE hint_04_gb  "../../data/gb/hint/04.bmp"  -1
IMAGE hint_05_gb  "../../data/gb/hint/05.bmp"  -1
IMAGE hint_06_gb  "../../data/gb/hint/06.bmp"  -1
IMAGE hint_07_gb  "../../data/gb/hint/07.bmp"  -1
IMAGE hint_08_gb  "../../data/gb/hint/08.bmp"  -1
IMAGE hint_09_gb  "../../data/gb/hint/09.bmp"  -1
